metrics:
  wal_directory: /var/lib/agent/wal
  global:
    scrape_interval: 60s
    external_labels:
      cluster: ${STACK_NAME}
      stack: ${STACK_NAME}
      shards: ${SHARDS}
  configs:
  - name: integrations
    remote_write:
    - url: ${GRAFANA_PROMETHEUS_URL}
      basic_auth:
        username: ${GRAFANA_PROMETHEUS_USER}
        password: ${GRAFANA_PROMETHEUS_PASSWORD}
    scrape_configs:
    - bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      job_name: integrations/kubernetes/cadvisor
      kubernetes_sd_configs:
          - role: node
      metric_relabel_configs:
          - source_labels: [__name__]
            regex: kubelet_running_pods|kube_deployment_status_replicas_available|node_quantile:kubelet_pleg_relist_duration_seconds:histogram_quantile|kubelet_runtime_operations_total|kube_daemonset_status_current_number_scheduled|kube_statefulset_status_replicas|kube_replicaset_owner|cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests|container_memory_swap|container_memory_cache|kube_daemonset_status_number_available|kubelet_running_containers|kube_resourcequota|container_cpu_usage_seconds_total|namespace_workload_pod|kubelet_node_config_error|kubelet_server_expiration_renew_errors|cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits|kubelet_running_pod_count|kube_horizontalpodautoscaler_status_current_replicas|kubelet_volume_stats_available_bytes|kube_node_status_capacity|kube_horizontalpodautoscaler_status_desired_replicas|kube_daemonset_status_updated_number_scheduled|kube_statefulset_status_update_revision|kube_daemonset_status_number_misscheduled|kube_statefulset_replicas|container_memory_rss|kubelet_pleg_relist_duration_seconds_bucket|kube_statefulset_status_current_revision|kube_deployment_status_replicas_updated|cluster:namespace:pod_memory:active:kube_pod_container_resource_requests|kube_node_info|kubelet_cgroup_manager_duration_seconds_bucket|kubelet_volume_stats_capacity_bytes|kube_job_status_start_time|kube_deployment_status_observed_generation|kube_node_spec_taint|kube_pod_container_resource_requests|kubelet_volume_stats_inodes_used|kube_job_failed|node_namespace_pod_container:container_memory_rss|storage_operation_errors_total|kube_pod_info|machine_memory_bytes|volume_manager_total_volumes|node_namespace_pod_container:container_memory_cache|kubelet_cgroup_manager_duration_seconds_count|namespace_memory:kube_pod_container_resource_limits:sum|kubernetes_build_info|kube_node_status_condition|node_namespace_pod_container:container_memory_swap|kube_pod_owner|kubelet_certificate_manager_client_expiration_renew_errors|kubelet_volume_stats_inodes|kube_job_status_active|cluster:namespace:pod_memory:active:kube_pod_container_resource_limits|kubelet_running_container_count|kube_node_status_allocatable|kubelet_pod_start_duration_seconds_count|kube_deployment_metadata_generation|kubelet_certificate_manager_client_ttl_seconds|node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate|process_cpu_seconds_total|kubelet_pod_worker_duration_seconds_count|namespace_cpu:kube_pod_container_resource_requests:sum|kube_daemonset_status_desired_number_scheduled|kube_statefulset_metadata_generation|kube_horizontalpodautoscaler_spec_min_replicas|container_cpu_cfs_throttled_periods_total|go_goroutines|process_resident_memory_bytes|kube_deployment_spec_replicas|node_namespace_pod_container:container_memory_working_set_bytes|kube_namespace_status_phase|kubelet_pod_worker_duration_seconds_bucket|kube_statefulset_status_replicas_ready|kube_statefulset_status_replicas_updated|container_memory_working_set_bytes|container_cpu_cfs_periods_total|namespace_cpu:kube_pod_container_resource_limits:sum|kube_pod_status_phase|namespace_workload_pod:kube_pod_owner:relabel|kubelet_pleg_relist_interval_seconds_bucket|rest_client_requests_total|kubelet_pleg_relist_duration_seconds_count|namespace_memory:kube_pod_container_resource_requests:sum|kube_horizontalpodautoscaler_spec_max_replicas|kube_pod_container_resource_limits|kubelet_node_name|kubelet_runtime_operations_errors_total|storage_operation_duration_seconds_count|kube_pod_container_status_waiting_reason|kube_statefulset_status_observed_generation|kube_namespace_status_phase|container_cpu_usage_seconds_total|kube_pod_status_phase|kube_pod_start_time|kube_pod_container_status_restarts_total|kube_pod_container_info|kube_pod_container_status_waiting_reason|kube_daemonset.*|kube_replicaset.*|kube_statefulset.*|kube_job.*|kube_node_status_capacity|node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate|cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests|namespace_cpu:kube_pod_container_resource_requests:sum
            action: keep
      relabel_configs:
          - replacement: kubernetes.default.svc.cluster.local:443
            target_label: __address__
          - regex: (.+)
            replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor
            source_labels:
              - __meta_kubernetes_node_name
            target_label: __metrics_path__
      scheme: https
      tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          insecure_skip_verify: false
          server_name: kubernetes
    - job_name: integrations/kubernetes/kube-state-metrics
      kubernetes_sd_configs:
          - role: pod
      metric_relabel_configs:
          - source_labels: [__name__]
            regex: kubelet_running_pods|kube_deployment_status_replicas_available|node_quantile:kubelet_pleg_relist_duration_seconds:histogram_quantile|kubelet_runtime_operations_total|kube_daemonset_status_current_number_scheduled|kube_statefulset_status_replicas|kube_replicaset_owner|cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests|container_memory_swap|container_memory_cache|kube_daemonset_status_number_available|kubelet_running_containers|kube_resourcequota|container_cpu_usage_seconds_total|namespace_workload_pod|kubelet_node_config_error|kubelet_server_expiration_renew_errors|cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits|kubelet_running_pod_count|kube_horizontalpodautoscaler_status_current_replicas|kubelet_volume_stats_available_bytes|kube_node_status_capacity|kube_horizontalpodautoscaler_status_desired_replicas|kube_daemonset_status_updated_number_scheduled|kube_statefulset_status_update_revision|kube_daemonset_status_number_misscheduled|kube_statefulset_replicas|container_memory_rss|kubelet_pleg_relist_duration_seconds_bucket|kube_statefulset_status_current_revision|kube_deployment_status_replicas_updated|cluster:namespace:pod_memory:active:kube_pod_container_resource_requests|kube_node_info|kubelet_cgroup_manager_duration_seconds_bucket|kubelet_volume_stats_capacity_bytes|kube_job_status_start_time|kube_deployment_status_observed_generation|kube_node_spec_taint|kube_pod_container_resource_requests|kubelet_volume_stats_inodes_used|kube_job_failed|node_namespace_pod_container:container_memory_rss|storage_operation_errors_total|kube_pod_info|machine_memory_bytes|volume_manager_total_volumes|node_namespace_pod_container:container_memory_cache|kubelet_cgroup_manager_duration_seconds_count|namespace_memory:kube_pod_container_resource_limits:sum|kubernetes_build_info|kube_node_status_condition|node_namespace_pod_container:container_memory_swap|kube_pod_owner|kubelet_certificate_manager_client_expiration_renew_errors|kubelet_volume_stats_inodes|kube_job_status_active|cluster:namespace:pod_memory:active:kube_pod_container_resource_limits|kubelet_running_container_count|kube_node_status_allocatable|kubelet_pod_start_duration_seconds_count|kube_deployment_metadata_generation|kubelet_certificate_manager_client_ttl_seconds|node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate|process_cpu_seconds_total|kubelet_pod_worker_duration_seconds_count|namespace_cpu:kube_pod_container_resource_requests:sum|kube_daemonset_status_desired_number_scheduled|kube_statefulset_metadata_generation|kube_horizontalpodautoscaler_spec_min_replicas|container_cpu_cfs_throttled_periods_total|go_goroutines|process_resident_memory_bytes|kube_deployment_spec_replicas|node_namespace_pod_container:container_memory_working_set_bytes|kube_namespace_status_phase|kubelet_pod_worker_duration_seconds_bucket|kube_statefulset_status_replicas_ready|kube_statefulset_status_replicas_updated|container_memory_working_set_bytes|container_cpu_cfs_periods_total|namespace_cpu:kube_pod_container_resource_limits:sum|kube_pod_status_phase|namespace_workload_pod:kube_pod_owner:relabel|kubelet_pleg_relist_interval_seconds_bucket|rest_client_requests_total|kubelet_pleg_relist_duration_seconds_count|namespace_memory:kube_pod_container_resource_requests:sum|kube_horizontalpodautoscaler_spec_max_replicas|kube_pod_container_resource_limits|kubelet_node_name|kubelet_runtime_operations_errors_total|storage_operation_duration_seconds_count|kube_pod_container_status_waiting_reason|kube_statefulset_status_observed_generation|kube_namespace_status_phase|container_cpu_usage_seconds_total|kube_pod_status_phase|kube_pod_start_time|kube_pod_container_status_restarts_total|kube_pod_container_info|kube_pod_container_status_waiting_reason|kube_daemonset.*|kube_replicaset.*|kube_statefulset.*|kube_job.*|kube_node_status_capacity|node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate|cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests|namespace_cpu:kube_pod_container_resource_requests:sum
            action: keep
      relabel_configs:
          - action: keep
            regex: kube-state-metrics
            source_labels:
              - __meta_kubernetes_pod_label_app_kubernetes_io_name
    - job_name: 'kubernetes-pods'
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: kubernetes_pod_name
      - action: labeldrop
        regex: 'instance|pod_template_hash|controller_revision_hash'
integrations:
  eventhandler:
    cache_path: /var/lib/agent/eventhandler.cache
    logs_instance: integrations
logs:
  configs:
  - name: integrations
    clients:
    - url: ${GRAFANA_LOGS_URL}
      basic_auth:
        username: ${GRAFANA_LOGS_USER}
        password: ${GRAFANA_LOGS_PASSWORD}
      external_labels:
        cluster: ${STACK_NAME}
        stack: ${STACK_NAME}
        shards: ${SHARDS}
        job: integrations/kubernetes/eventhandler
    positions:
      filename: /tmp/positions.yaml
    target_config:
      sync_period: 10s
