apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: temporal-rules
  namespace: monitoring
spec:
  groups:
  - name: temporal-metrics
    rules:
    - alert: TemporalRequestLatencyHigh
      annotations:
        description: Temporal {{ $labels.operation }} request latency is currently {{ $value | humanize }}, outside of SLO 150ms.
        summary: Temporal request latency is too high.
      expr: |
        histogram_quantile(0.95, sum by (le, operation) (rate(temporal_request_latency_bucket{job="benchmark-monitoring",operation="StartWorkflowExecution"}[5m])))
        > 0.150
      for: 5m
      labels:
        namespace: temporal
        severity: critical
    # - alert: TemporalShardLockLatencyHigh
    #   annotations:
    #     description: Temporal shard lock latency is currently {{ $value | humanize }}, outside of SLO of 1ms.
    #     summary: Temporal shard lock latency is too high.
    #   expr: |
    #     histogram_quantile(0.95, sum by (le) (rate(lock_latency_bucket[5m])))
    #     > 0.001
    #   for: 5m
    #   labels:
    #     namespace: temporal
    #     severity: critical