apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: benchmark-workers
    app.kubernetes.io/component: workers
  name: benchmark-workers
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: benchmark-workers
      app.kubernetes.io/component: workers
  template:
    metadata:
      labels:
        app.kubernetes.io/name: benchmark-workers
        app.kubernetes.io/component: workers
    spec:
      initContainers:
        - name: create-namespace
          image: temporalio/admin-tools:1.19.1
          env:
          - name: TEMPORAL_CLI_ADDRESS
            value: "temporal-frontend:7233"
          command: ["bash", "-c"]
          args: ["tctl --namespace default namespace register || tctl --namespace default namespace describe"]
      containers:
      - image: ghcr.io/temporalio/benchmark-workers:main
        imagePullPolicy: Always
        name: benchmark-workers
        env:
        - name: TEMPORAL_GRPC_ENDPOINT
          value: "temporal-frontend:7233"
        - name: PROMETHEUS_ENDPOINT
          value: 0.0.0.0:8000
        - name: TEMPORAL_NAMESPACE
          value: "default"
        - name: TEMPORAL_TASK_QUEUE
          value: "benchmark"
        envFrom:
        - configMapRef:
            name: benchmark-worker-env          
        ports:
        - name: metrics
          containerPort: 8000
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
      restartPolicy: Always