apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: benchmark
    app.kubernetes.io/component: soak-test
  name: benchmark-soak-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: benchmark
      app.kubernetes.io/component: soak-test
  template:
    metadata:
      labels:
        app.kubernetes.io/name: benchmark
        app.kubernetes.io/component: soak-test
    spec:
      initContainers:
        - name: create-namespace
          image: temporalio/admin-tools:1.20.0
          env:
          - name: TEMPORAL_CLI_ADDRESS
            value: "temporal-frontend.temporal.svc.cluster.local:7233"
          command: ["bash", "-c"]
          args: ["tctl --namespace default namespace register || tctl --namespace default namespace describe"]
      containers:
      - image: ghcr.io/temporalio/benchmark-workers:main
        imagePullPolicy: Always
        name: benchmark-soak-test
        command: ["runner", "-w", "-c", "$(CONCURRENT_WORKFLOWS)", "-t", "ExecuteActivity", '{ "Count": 3, "Activity": "Echo", "Input": { "Message": "test" } }']
        env:
        - name: TEMPORAL_GRPC_ENDPOINT
          value: "dns:///temporal-frontend.temporal.svc.cluster.local:7233"
        - name: PROMETHEUS_ENDPOINT
          value: 0.0.0.0:8000
        - name: TEMPORAL_NAMESPACE
          value: "default"
        - name: TEMPORAL_TASK_QUEUE
          value: "benchmark"
        envFrom:
        - configMapRef:
            name: benchmark-soaktest-env
        ports:
        - name: metrics
          containerPort: 8000
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 32Mi
          limits:
            cpu: 200m
            memory: 64Mi
      restartPolicy: Always