global:
  scrape_interval: 10s
scrape_configs:
  - job_name: 'temporal'
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - 'temporal:8000'
          - 'benchmark-workers:8000'
