apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal-postgres
  labels:
    app.kubernetes.io/name: temporal-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: temporal-postgres
  template:
    metadata:
      labels:
        app.kubernetes.io/name: temporal-postgres
    spec:
      containers:
        - env:
            - name: POSTGRES_PASSWORD
              value: temporal
            - name: POSTGRES_USER
              value: temporal
          image: postgres:13
          name: temporal-postgresql
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: temporal-postgres
  name: temporal-postgres
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    app.kubernetes.io/name: temporal-postgres
