apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal-frontend
spec:
  template:
    spec:
      initContainers:
      - name: schema
        image: temporalio/auto-setup:1.17.2
        imagePullPolicy: IfNotPresent
        command: ["/etc/temporal/auto-setup.sh"]
        env:
        - name: DB
          value: postgresql
        - name: DB_PORT
          value: "5432"
        - name: POSTGRES_SEEDS
          value: temporal-postgres
        - name: POSTGRES_USER
          value: temporal
        - name: POSTGRES_PWD
          value: temporal
        - name: DBNAME
          value: temporal
        - name: VISIBILITY_DBNAME
          value: temporal_visibility
