apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal-mysql
  labels:
    app.kubernetes.io/name: temporal-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: temporal-mysql
  template:
    metadata:
      labels:
        app.kubernetes.io/name: temporal-mysql
    spec:
      containers:
        - env:
          - name: MYSQL_ROOT_PASSWORD
            value: root
          image: mysql:8
          name: temporal-mysql
          ports:
            - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: temporal-mysql
  name: temporal-mysql
spec:
  ports:
    - name: "3306"
      port: 3306
      targetPort: 3306
  selector:
    app.kubernetes.io/name: temporal-mysql
