apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: benchmark-monitor
  labels:
    app.kubernetes.io/name: benchmark-workers
    app.kubernetes.io/component: monitoring
spec:
  endpoints:
  - port: metrics
    interval: 30s
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app.kubernetes.io/name: benchmark-workers
      app.kubernetes.io/component: monitoring
