apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    batch.kubernetes.io/job-tracking: ""
  labels:
    app.kubernetes.io/managed-by: pulumi
  name: temporal-autosetup
  namespace: temporal
spec:
  backoffLimit: 300
  completionMode: NonIndexed
  completions: 1
  parallelism: 1
  suspend: false
  template:
    metadata:
      labels:
        batch.kubernetes.io/job-name: temporal-autosetup
        job-name: temporal-autosetup
    spec:
      containers:
      - command:
        - /etc/temporal/auto-setup.sh
        envFrom:
        - configMapRef:
            name: temporal-env
        image: temporalio/auto-setup:1.20.0
        imagePullPolicy: IfNotPresent
        name: autosetup
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: extra
          mountPath: /etc/temporal-extra/
      volumes:
      - name: extra
        configMap:
          name: temporal-extras
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
