apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: history
    app.kubernetes.io/instance: temporal
    app.kubernetes.io/name: temporal
    app.kubernetes.io/part-of: temporal
    app.kubernetes.io/version: 1.17.2
  name: temporal-history
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: history
      app.kubernetes.io/instance: temporal
      app.kubernetes.io/name: temporal
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8000'
      labels:
        app.kubernetes.io/component: history
        app.kubernetes.io/instance: temporal
        app.kubernetes.io/name: temporal
        app.kubernetes.io/part-of: temporal
        app.kubernetes.io/version: 1.17.2
    spec:
      containers:
      - env:
        - name: BIND_ON_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: SERVICES
          value: history
        - name: PROMETHEUS_ENDPOINT
          value: 0.0.0.0:8000
        envFrom:
        - configMapRef:
            name: temporal-persistence-env
        image: temporalio/server:1.17.2
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 150
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: rpc
          timeoutSeconds: 1
        name: temporal
        ports:
        - containerPort: 7234
          name: rpc
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/temporal/dynamic_config
          name: dynamic-config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: dynamic_config.yaml
            path: dynamic_config.yaml
          name: temporal-dynamic-config
        name: dynamic-config