apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: worker
    app.kubernetes.io/instance: temporal
    app.kubernetes.io/name: temporal
    app.kubernetes.io/part-of: temporal
    app.kubernetes.io/version: 1.18.0
  name: temporal-worker
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: worker
      app.kubernetes.io/instance: temporal
      app.kubernetes.io/name: temporal
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/component: worker
        app.kubernetes.io/instance: temporal
        app.kubernetes.io/name: temporal
        app.kubernetes.io/part-of: temporal
        app.kubernetes.io/version: 1.18.0
    spec:
      containers:
      - env:
        - name: BIND_ON_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: SERVICES
          value: worker
        - name: PUBLIC_FRONTEND_ADDRESS
          value: temporal-frontend:7233
        - name: PROMETHEUS_ENDPOINT
          value: 0.0.0.0:8000
        envFrom:
        - configMapRef:
            name: temporal-env
        image: temporalio/server:1.18.0
        imagePullPolicy: IfNotPresent
        name: temporal
        ports:
        - name: rpc
          containerPort: 7239
          protocol: TCP
        - name: metrics
          containerPort: 8000
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/temporal/dynamic_config
          name: dynamic-config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: dynamic_config.yaml
            path: dynamic_config.yaml
          name: temporal-dynamic-config
        name: dynamic-config