apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal-frontend
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal-worker
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal-matching
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal-history
spec:
  replicas: 1