apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: frontend
    app.kubernetes.io/instance: temporal
    app.kubernetes.io/name: temporal
    app.kubernetes.io/part-of: temporal
    app.kubernetes.io/version: 1.20.0
  name: temporal-frontend
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: frontend
      app.kubernetes.io/instance: temporal
      app.kubernetes.io/name: temporal
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/component: frontend
        app.kubernetes.io/instance: temporal
        app.kubernetes.io/name: temporal
        app.kubernetes.io/part-of: temporal
        app.kubernetes.io/version: 1.20.0
    spec:
      containers:
      - env:
        - name: BIND_ON_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: SERVICES
          value: frontend
        - name: USE_INTERNAL_FRONTEND
          value: '1'
        - name: PROMETHEUS_ENDPOINT
          value: 0.0.0.0:8000
        - name: DYNAMIC_CONFIG_FILE_PATH
          value: /etc/temporal/dynamic_config/dynamic_config.yaml
        envFrom:
        - configMapRef:
            name: temporal-env
        image: temporalio/server:1.20.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 150
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: rpc
          timeoutSeconds: 1
        name: temporal
        ports:
        - name: rpc
          containerPort: 7233
          protocol: TCP
        - name: metrics
          containerPort: 8000
          protocol: TCP
        resources:
          requests:
            cpu: 1000m
            memory: 256Mi
          limits:
            cpu: 1500m
            memory: 768Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/temporal/dynamic_config
          name: dynamic-config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: dynamic_config.yaml
            path: dynamic_config.yaml
          name: temporal-dynamic-config
        name: dynamic-config