apiVersion: v1
kind: Service
metadata:
  name: temporal-frontend
  labels:
    app.kubernetes.io/component: frontend
    app.kubernetes.io/instance: temporal
    app.kubernetes.io/name: temporal
    app.kubernetes.io/part-of: temporal
    app.kubernetes.io/version: 1.18.0
spec:
  internalTrafficPolicy: Cluster
  ports:
  - name: grpc-rpc
    port: 7233
    protocol: TCP
    targetPort: rpc
  selector:
    app.kubernetes.io/component: frontend
    app.kubernetes.io/instance: temporal
    app.kubernetes.io/name: temporal
  sessionAffinity: None
  type: ClusterIP
  clusterIP: None
