apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: internal-frontend
    app.kubernetes.io/instance: temporal
    app.kubernetes.io/name: temporal
    app.kubernetes.io/part-of: temporal
    app.kubernetes.io/version: 1.18.0
  name: temporal-internal-frontend
spec:
  internalTrafficPolicy: Cluster
  ports:
  - name: grpc-rpc
    port: 7236
    protocol: TCP
    targetPort: rpc
  selector:
    app.kubernetes.io/component: internal-frontend
    app.kubernetes.io/instance: temporal
    app.kubernetes.io/name: temporal
  sessionAffinity: None
  type: ClusterIP
