name: Run Benchmarks
on:
  - workflow_dispatch 
jobs:
  benchmarks:
    name: Run benchmarks
    strategy:
      matrix:
        stack: [eks-rds-postgres-m6i-large]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18.x
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE }}
      - run: go mod download
      - shell: bash
        env:
          MONITORING_ENV: ${{ secrets.MONITORING_ENV }}
        run: echo "${MONITORING_ENV}" > k8s/monitoring/.env.grafana
      - uses: pulumi/actions@v3
        with:
          work-dir: k8s/stacks
          command: up
          stack-name: ${{ matrix.stack }}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_TOKEN }}
      - uses: pulumi/actions@v3
        if: always()
        with:
          work-dir: k8s/stacks
          command: destroy
          stack-name: ${{ matrix.stack }}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_TOKEN }}
